### ISSUE TITLE
global namespace

### ISSUE THREAD

**Issue by andreluizbarbieri** [nvpro-samples/gl_cadscene_rendertechniques#2]
Compile error: 'int_least8_t': is not member of 'global namespace'

**Comment by pixeljetstream** [comment]
which compiler are you using and what file is that coming from?

**Comment by andreluizbarbieri** [comment]
Hi, thanks for attention. I compile the solution with VS2015 via Cmake -G "Visual Studio 14 Win64", but in compile phase occur this error about "'int_least8_t': is not member of 'global namespace'" and many others equals.

**Comment by obelloc** [comment]
Hello, I managed to solve that by removing the file `shared_external/NSight/stdint.h` from the build. You should not need this file when using VS2015 anyway.

When  `shared_external/NSight` is added to the include directories. Whenever a include for `stdint.h`  is reached, I guess Visual Studio considers the local `stdint.h`, instead of the standard one.

**Comment by pixeljetstream** [comment]
thanks a lot, we probably forgot deleting this, as I think on our internal version of shared_sources it's already gone
